#url: https://uielinux.github.io
url: http://uielinux.org
baseurl:

# Site settings
title: UieLinux
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff6600
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Sergio Gridelli
  pic: 1.png
  position: Presidente
  social:
    - title: twitter
      url: https://twitter.com/giowile
    - title: facebook
      url: https://www.facebook.com/sergiogridelli
    - title: google-plus
      url: https://plus.google.com/u/0/+SergioGridelli

- name: Stefano Teodorani
  pic: 2.png
  position: Vice Presidente
  social:
    - title: twitter
      url: https://twitter.com/teopost
    - title: facebook
      url: https://www.facebook.com/steodorani
    - title: google-plus
      url: https://plus.google.com/+StefanoTeodorani

- name: Christian Galeffi
  pic: 3.png
  position: Consigliere
  social:
    - title: twitter
      url: https://twitter.com/gallochri
    - title: facebook
      url: https://www.facebook.com/gallochri
    - title: google-plus
      url: https://plus.google.com/u/0/+ChristianGaleffi

- name: Davide Pedrelli
  pic: 4.png
  position: Consigliere
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Marco Sgarzi
  pic: 5.png
  position: Consigliere
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Carlo Zamagni
  pic: 6.png
  position: Consigliere
  social:
    - title: twitter
      url: https://twitter.com/czamagni
    - title: google-plus
      url: https://plus.google.com/u/0/+CarloZamagni/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/uielinux
  - title: facebook
    url: https://www.facebook.com/uielinux.org
  - title: G+
    url: google.com/+UielinuxOrgItalia
  - title: github
    url: https://github.com/UieLinux

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

costituzione: /static/UIE_Atto-Costitutivo.pdf
statuto: /statuto/UIE_Statuto.pdf
